### PR TITLE
Add new gamelab favicons

### PR DESCRIPTION
**Pull request by maxwofford**
Screen Shot 2022-02-28 at 12 16 42
Screen Shot 2022-02-28 at 12 16 49
Screen Shot 2022-02-28 at 12 17 06

### CODE REVIEW

**Comment by cedric-h** [comment]
SO GOOD

**Comment by YodaLightsabr** [comment]
@maxwofford The error handling shouldn't look like that; what browser are you on?

**Comment by maxwofford** [comment]
@YodaLightsabr Firefox developer edition

**Comment by YodaLightsabr** [comment]
I just tried it and I can reproduce it on multiple browsers. Do you know if someone accidentally removed it?

**Comment by maxwofford** [comment]
not sure, cc @leomcelroy @cedric-h

**Pull request merged**
